ploeh/ploeh.github.com

_posts/2014-11-18-the-isnullorwhitespace-trap.html

... for those of us still staring wide-eyed at the Functional Programming monolith ;)

Add link for functional programming term 'Fold'

---

_posts/2015-01-19-from-primitive-obsession-to-domain-modelling.html

Dear Mark, I wrote a comment under your nice article!

Comment - It's also good OO, imho

---

_posts/2015-01-19-from-primitive-obsession-to-domain-modelling.html

Added Comment to Primitive Object

Added Comment to Primitive Object

---

_posts/2009-03-11-ExplicitExpectations.html

The code I added is not formatted, at the moment. I don't know how to do that. Do I need to do that by hand, or do you have some tool, or webapp that can do that?
ps I really enjoy reading your blog, and your book was realy insightful ;)

Add comment to Explicit Expectations page.

---

_posts/2013-04-30-rest-lesson-learned-avoid-204-responses.html

Comment disagreeing with your statement about DELETE and 204.

Add comment to the avoid 204 responses post

---

_posts/2013-05-01-rest-lesson-learned-avoid-hackable-urls.html

This branch adds a comment on how we planned to combat client side URL construction and signing.

Combatting client side url construction

---

_posts/2015-04-13-less-is-more-language-features.html

Commenting on "less-is-more-language-features"

Commenting

---

_posts/2015-06-22-rest-implies-content-negotiation.html

Thanks for blogging Mark. Your abstract interfaces blew my mind!
In my comment there is something useful about content negotiation you may not have seen.

comment on 5 levels of media type

---

_posts/2012-11-06-WhentouseaDIContainer.html

A comment to your 2012 post "When to use a DI Container", with a reference to the article "An AutoFac Lifetime primer".

A comment to When to use a DI Container

---

_posts/2015-09-18-temporary-field-code-smell.html

Add comment by Tom Kerkhove

---

_posts/2015-09-18-temporary-field-code-smell.html

Add additional comment by Tom Kerkhove, thanks for replying!
Relates to PR #192.

Add additional comment by Tom Kerkhove

---

_posts/2015-09-23-applications-and-their-side-effects.html

Comment providing reference to CQ(R)S usage warning.

CQS reference warning

---

_posts/2015-10-08-command-query-separation-when-queries-should-have-side-effects.html

Another option would be to send a notification, but it is at the cost of some indirection.

Commented CQS when Queries should have side-effects

---

_posts/2015-06-22-rest-implies-content-negotiation.html

Adding a comment. 
You can also see that I accidentally removed trailing spaces from the end three lines, thanks to my text editor's onSave formatting task.

add comment to 2015-06-22-rest-implies-content-negotiation.html

---

_posts/2015-10-26-service-locator-violates-encapsulation.html

Comment added to Service Locator violates encapsulation post

Service Locator violates encapsulation comment

---

_posts/2015-10-26-service-locator-violates-encapsulation.html

Added comment asking if usage of Service Locator is only an anti-pattern if used in certain contexts. First comment on your blog... let me know if there's anything lacking.

Add comment to "Service Locator violates encapsulation"

---

_posts/2015-01-19-from-primitive-obsession-to-domain-modelling.html

Adding a comment to http://blog.ploeh.dk/2015/01/19/from-primitive-obsession-to-domain-modelling/

Adding a comment

---

_posts/2014-01-29-nuget-package-restore-considered-harmful.html

Adding a comment. Have no idea if this is how you intended it to be done. :)

Adding Comment

---

_posts/2011-12-21-TestingContainerConfigurations.html

I felt my wording was a little harsh

Updated wording

---

_posts/2013-05-01-rest-lesson-learned-avoid-hackable-urls.html

Thanks for considering my comment, even though it's quite late.

Add comment about hackable URIs.

---

_posts/2013-05-01-rest-lesson-learned-avoid-hackable-urls.html

Reply to comment on URI templates

---

_posts/2016-03-18-functional-architecture-is-ports-and-adapters.html

Added comment to post about functional architecture

Added comment to post functional architecture

---

_posts/2016-03-18-functional-architecture-is-ports-and-adapters.html

Responded to question in post _Functional architecture is Ports and Adapters_

Responded to question

---

_posts/2016-03-18-functional-architecture-is-ports-and-adapters.html

Hopefully I've structured this pull request correctly -- I don't do a lot of this on GitHub!
Thanks so much for the work you do!

New comment on post from March 18

---

_posts/2016-03-18-functional-architecture-is-ports-and-adapters.html

Hi Mark,
Here's a brief followup comment if you're interested

Followup Comment

---

_posts/2013-03-03-moving-the-blog-to-jekyll.html

the page http://blog.ploeh.dk/about.html doesn't exist, but http://blog.ploeh.dk/about/ does exist

[fix] link to 'about' page

---

_posts/2016-05-06-cqs-and-server-generated-entity-ids.html

Hopefully, managed the mark-up correctly.

Comment to CQS and server-generated Entity IDs

---

_posts/2015-01-19-from-primitive-obsession-to-domain-modelling.html

Added my comment and fixed typo in the timestamp of previous comment.

added comment

---

_posts/2016-03-18-functional-architecture-is-ports-and-adapters.html

Hi Mark,
I've added a comment to your post Functional architecture is Ports and Adapters. I'd be happy to hear what you think!

Add comment to functional-ports-and-adapters

---

_posts/2013-09-12-di-and-events-composition.html

Comment on DI and Events series of posts.

comment about using Action instead of IObserver.

---

_posts/2016-07-04-conditional-composition-of-functions.html

Hi Mark,
Many thanks for this post. I've added my comments at the end, and I think I've learned a lot from this exchange!

Add my comment to conditional-composition post

---

_posts/2016-11-28-easy-domain-modelling-with-types.html

I added a comment on your latest article.

Add comment on Easy domain modeling with types

---

_posts/2016-03-18-functional-architecture-is-ports-and-adapters.html

This is a follow up of my twitter's comments about I/O in pure functions and the concrete benefits of Haskell-like purity

Commenting 2016-03-18-functional-architecture-is-ports-and-adapters.html

---

_posts/2016-03-18-functional-architecture-is-ports-and-adapters.html

I've posted a reply to better clarify my initial comments

comment to 2016-03-18-functional-architecture-is-ports-and-adapters.html

---

_posts/2013-10-15-easy-aspnet-web-api-dtos-with-f-climutable-records.html

Comment with a question about how the Json serialization of immutable F# records work.

Add comment about Json serialization of records

---

_posts/2016-05-06-cqs-and-server-generated-entity-ids.html

We can use SQL Server sequence as running number generator service.

Using SQL Server sequence

---

_posts/2017-01-03-decoupling-application-errors-from-domain-models.html

The PR adds a comments section and asks a question in the comments.

Question about HttpStatusCodes in domain model.

---

_posts/2014-06-02-captive-dependency.html

Added a comment about how to solve the captive dependency proplem.

commented 2014-06-02-captive-dependency.html

---

_posts/2014-06-13-passive-attributes.html

Thanks for the post, I tried to do the same for a class attribute (AttributeTargets.Class) and I am getting a null object every time I get the custom attributes. Does this only work for Methods? Or how can I make it work with classes? Thanks.

Added comment.

---

_posts/2017-04-24-simple-holidays.html

The view is not tested. I'm betting on you testing that the comment looks OK :-)

Added comment about holiday calculations

---

_posts/2013-02-04-BewareofProductivityTools.html

Comment on Productivity Tool

---

_posts/2016-03-18-functional-architecture-is-ports-and-adapters.html

Add a reply to @MartinRykfors' comment.

Add comment reply to "ports and adapters"

---

_posts/2013-12-10-semantic-versioning-with-continuous-deployment.html

Blog comment about automation workflow for merge

Blog comment to 2013-12-10 Semantic Versioning about automation workflow

---

_posts/2017-08-15-test-data-builders-in-c.html

My first attempt at a comment.  Hope it looks OK. 😄

Adding comment regarding immutability and command/query separation.

---

_posts/2017-08-21-generalised-test-data-builder.html

Comment : C# Object Initializer

Comment : C# Object Initializer

---

_posts/2017-08-21-generalised-test-data-builder.html

Comment : Thanks for clarification

Comment : Thanks for clarification

---

_posts/2015-08-03-idiomatic-or-idiosyncratic.html

Add a comment on http://blog.ploeh.dk/2015/08/03/idiomatic-or-idiosyncratic/ to end the javascript loop

:speech_balloon: add comment to idiomatic post

---

_posts/2012-10-03-DependencyInjectioninASP.NETWebAPIwithCastleWindsor.html

curious about the container being registered in the constructor since WebApplication's constructor is called multipel times on startup and on each request.  thank you!

Comment on WebAPI DI constructor vs Application_start.

---

_posts/2017-10-05-monoids-semigroups-and-friends.html

I left a comment in the article titled ["_Monoids, semigroups and friends_"](http://blog.ploeh.dk/2017/10/05/monoids-semigroups-and-friends/).

Adds a comment to the 'Monoids, semigroups and friends' post

---

_posts/2017-10-05-monoids-semigroups-and-friends.html

converse: Engage in conversation
inverse: opposite, contrary

Correct term for 'opposite' in monoid,semigroup article

---

_posts/2017-10-05-monoids-semigroups-and-friends.html

referring to Kent Beck's notion of Monoids, "I don't think he ever explicitly calls it" I think should be "..calls it out" or "says it"

Possible Typo

---

_posts/2017-10-06-monoids.html

A question regarding removing ambiguity around overloaded meanings of the word closure.

A question about the use of the word closure

---

_posts/2017-09-18-the-test-data-generator-functor.html

Adds comment to post on Test Data Generator functor

Add comment to post

---

_posts/2017-11-06-function-monoids.html

I apologize if I got it wrong though...

Placed comma at the appropriate position

---

_posts/2018-02-26-inheritance-composition-isomorphism.html

It's not very obvious what exactly 'Data' means in this context. I could be wrong, though.

Removed 'Data' from a comment

---

_posts/2018-02-19-abstract-class-isomorphism.html

Added a comment about language agnosticism

Comment to Abstract class isomorphism

---

_posts/2018-02-19-abstract-class-isomorphism.html

Comment response to http://blog.ploeh.dk/2018/02/19/abstract-class-isomorphism/#7aac063a684047ae9561c6666a42f908

Added comment response

---

_posts/2011-05-26-CodeSmellAutomaticProperty.html

Added a simple comment on the following article:
http://blog.ploeh.dk/2011/05/26/CodeSmellAutomaticProperty/
Parts of the article would do well with an update considering new language features like readonly automatic properties.

Comment on property code smell article.

---

_posts/2018-02-19-abstract-class-isomorphism.html

**Work in progress**
What code highlighter do you use? I have some code examples in the comment but I'm not sure how to add proper highlighting so that it matches the highlighting style of your code.

Added a comment to "Abstract class isomorphism".

---

_posts/2018-04-23-null-object-as-identity.html

Added the first comment to the null object as identity comment post.

Add null object as identity comment

---

_posts/2018-05-14-project-arbitraries-with-view-patterns.html

I also fixed the type signature in my last comment :)

Answered your questions

---

_posts/2014-08-11-cqs-versus-server-generated-ids.html

Added question on how Mark would go about designing a repository layer.

Added Comment asking Mark a Question

---

_posts/2018-06-18-church-encoded-payment-types.html

Fixed a minor typo in the second code block of the http://blog.ploeh.dk/2018/06/18/church-encoded-payment-types/ post.

Added missing character in parameter name.

---

_posts/2018-03-22-functors.html

a comment providing (for any interested reader) a diagrammatic potential aid to internalising functor laws.

add comment to functors page

---

_posts/2018-10-29-the-maybe-applicative-functor.html

I added a comment about currying in C# to your "The Maybe applicative functor" article.  I hope you don't think I am being too nit picky by pointing out the same thing as I did before but this time on another article.

comment in article on maybe applicative functor about currying in C#

---

_posts/2017-09-18-the-test-data-generator-functor.html

The comment has a link to some examples of using Hedgehog from C#:
https://github.com/moodmosaic/fsharp-hedgehog/blob/master/tests/Hedgehog.CSharp.Tests/LinqTests.cs

Added a comment to a post

---

_posts/2017-10-16-money-monoid.html

Fix small typo

---

_posts/2018-11-19-functional-architecture-a-definition.html

Here are my cents on the subject. Thx again for the article.

Comment on Functional Architecture definition

---

_posts/2018-06-11-church-encoded-either.html

A tiny curiosity regarding Eithers.

Added question to Either article

---

_posts/2014-05-19-di-friendly-framework.html

thank you so much for any advice

trying to post, fingers crossed

---

_posts/2019-02-11-asynchronous-injection.html

I didn't add a comment id, how do you generate one?

Comment on 2019-02-11-asynchronous-injection.html

---

_posts/2019-02-11-asynchronous-injection.html

Corrected typo

---

_includes/custom/comments
_includes/themes/bootstrap-3/post.html
_includes/themes/ploeh/default.html
_includes/themes/ploeh/post.html
_includes/themes/twitter/post.html
index.html

add hidden-print to unneeded sections

---

_posts/2019-02-11-asynchronous-injection.html

Add a comment to 2019-02-11-asynchronous-injection.html

Add a comment

---

_posts/2019-02-11-asynchronous-injection.html

I am pretty sure there is a small grammar mistake here and that this is the intended wording

replace "The" with "This" to fix a typo

---

_posts/2009-01-28-Zero-FrictionTDD.html
_posts/2011-05-24-Poka-yokeDesignFromSmelltoFragrance.html
_posts/2013-01-07-RoleHints.html
_posts/2013-02-06-StringCalculatorkatawithAutoFixture.html
_posts/2013-04-29-rest-lessons-learned.html
_posts/2013-09-06-dependency-injection-and-events.html
_posts/2015-08-10-type-driven-development.html
_posts/2016-02-10-types--properties--software.html
_posts/2017-01-27-from-dependency-injection-to-dependency-rejection.html
_posts/2017-06-27-pure-times.html
_posts/2017-07-10-pure-interactions.html
_posts/2017-08-14-from-test-data-builders-to-the-identity-functor.html
_posts/2017-10-4-from-design-patterns-to-category-theory.html
_posts/2019-02-18-from-interaction-based-to-state-based-testing.html

This is based on a discussion had at
https://github.com/ploeh/ploeh.github.com/issues/389#issuecomment-463201337
In short, the purpose of the tag is to identify the entry points to
various article series.

Added Article Series tag

---

_posts/2017-09-11-test-data-without-builders.html

Comments about generating builders

Comment on '2017-09-11-test-data-without-builders.html'

---

_posts/2019-03-18-the-programmer-as-decision-maker.html

comment on The programmer as decision maker

---

README.md

update readme : add blog url + fix path to first post

---

_posts/2019-04-01-an-example-of-state-based-testing-in-c.html

Question for An example of state-based testing in C#

ladeak comment for An example of state-based testing in C#

---

_posts/2019-02-11-asynchronous-injection.html

Looking forward to a reply.
Thank you!

A comment to the "Asynchronous Injection" post

---

_posts/2019-08-05-rose-tree-catamorphism.html

Great post! Helped me get precisely what a Rose Tree *is*, which I've originally learned by osmosis...

Fixed a small typo

---

_posts/2019-09-09-picture-archivist-in-haskell.html

A comment regarding lazy evaluation and space limits.

Comment on haskell pictures archivist

---

_includes/themes/ploeh/default.html

Use bootstrap [static top navbar](https://getbootstrap.com/docs/3.3/components/#navbar-static-top)

remove rounded border from navbar

---

index.html

Hi @ploeh 
I read your blog from time to time, and have fixed the incorrect 'next' link on page 2
Fixes #246

Fix incorrect 'next' link on page 2

---

_posts/2017-08-07-f-free-monad-recipe.html

Suggesting to talk about operation rather than member

Post comment

---

_posts/2018-11-19-functional-architecture-a-definition.html

P. S. Adding comments on iPad is really painful… 😄

Comment: Should intention be considered?

---

_posts/2019-12-02-refactoring-registration-flow-to-functional-architecture.html

Hope everything's formatted correctly!

Add comment

---

_posts/2019-12-02-refactoring-registration-flow-to-functional-architecture.html

Thanks for fixing my broken link in my previous comment :)

added an example of a pure-impure-pure-impure composition

---

_posts/2019-12-09-put-cyclomatic-complexity-to-good-use.html

I'd like to hear your thoughts on mutation testing and whether it affects your perspective on code coverage. Thanks!
PS: By the way, the comment contains a link to a post I wrote for a company's blog. I wasn't sure whether it was ok or not to add the link but, of course, feel free to remove it if you feel like it.

Add comment to the "Put cyclomatic complexity to good use." post.

---

_posts/2019-12-16-zone-of-ceremony.html

Sorry. I discovered some whitespace issues after reading the updated article.

Fix whitespaces in my comment

---

_posts/2018-06-25-visitor-as-a-sum-type.html

Changed "distinguishes" to "distinguish" to have the multiplicity of the verb match the subject.

grammar improvement

---

_posts/2014-08-24-decoraptor.html

Added additional response

---

_posts/2014-08-24-decoraptor.html

Comment #5

---

_posts/2020-02-24-discerning-and-maintaining-purity.html

@ymassad, I ask you a question in this comment

comment about how the simplest overload of DateTime.TryParse is impure

---

_posts/2015-05-07-functional-design-is-intrinsically-testable.html

I accidentally deleted my branch from my fork, which caused #573 to be closed.  Sorry about that.

asked if a pure function can throw an exception

---

_posts/2020-02-24-discerning-and-maintaining-purity.html

I am absolutely loving our conversations about purity.  Thank you very much joining me as I unpack this definition about which [you said](https://blog.ploeh.dk/2015/05/07/functional-design-is-intrinsically-testable/#8357b5ab8ada4f44bf17dcacd9b9b079)
> It seems to me to be a standard and non-controversial definition.
;P

comment digging deeper into the definition of purity

---

_posts/2014-01-22-a-functional-architecture-with-f.html
_posts/2014-01-29-nuget-package-restore-considered-harmful.html
_posts/2015-05-07-functional-design-is-intrinsically-testable.html
_posts/2017-09-11-test-data-without-builders.html
_posts/2018-10-15-an-applicative-password-list.html
_posts/2018-10-29-the-maybe-applicative-functor.html
_posts/2019-01-07-either-bifunctor.html
_posts/2019-02-11-asynchronous-injection.html
_posts/2019-04-22-applicative-monoids.html
_posts/2019-04-29-catamorphisms.html
_posts/2019-10-07-devils-advocate.html
_posts/2019-10-21-a-red-green-refactor-checklist.html
_posts/2019-11-18-small-methods-are-easy-to-troubleshoot.html
_posts/2019-12-02-refactoring-registration-flow-to-functional-architecture.html
_posts/2019-12-09-put-cyclomatic-complexity-to-good-use.html
_posts/2019-12-16-zone-of-ceremony.html
_posts/2020-02-03-non-exceptional-averages.html
_posts/2020-02-10-builder-isomorphisms.html
_posts/2020-02-24-discerning-and-maintaining-purity.html
_posts/2020-03-09-polymorphic-builder.html

Hello Mark.
Do you mind if I add links from my name on comment author lines to a personal page of mine?
I appreciate your consideration :)

added hyperlinks from my comment author lines to my about.me page

---

_posts/2020-03-30-repeatable-execution-in-haskell.html

1 comment about how to handle more complex cases and the limits of the Free Monad.

Repeatable executions in Haskell: 1 comment

---

_posts/2020-04-20-unit-bias-against-collections.html

The PR workflow is a bit more time consuming, but I start to like it for the flexibility ;-)

Add response

---

_posts/2019-09-30-10x-developers.html

added my comment

---

_posts/2019-09-16-picture-archivist-in-f.html

added a comment that touches on three things in the picture archivist in F# article

comment on picture archivist in F# article

---

_posts/2019-02-11-asynchronous-injection.html

What a curious way to write comments.
Feels quite uneasy. Hopefully I've understood your intent. Sorry, I couldn't really figure out how to generate a comment id.

Comment on async injection.

---

_posts/2018-11-19-functional-architecture-a-definition.html

I spend 20 minutes on my phone for this small segment, sorry if I missed something ^^
The id is something that I did not find documented, neither here in your repo, nor in the Jekkyl documentation.
Please, forgive me :D

Add comment about Nim

---

_posts/2020-12-21-a-haskell-proof-of-concept-of-validation-with-partial-data-round-trip.html

That `Endo` is `Data.Monoid.Endo`, right?  Is this a good link to put there?

added link to Data.Monoid.Endo

---

_posts/2020-12-28-an-f-demo-of-validation-with-partial-data-round-trip.html

swapped "is here" to "here is"
replaced "that" with "now"
replaced "satisfactory" with "satisfying"

fixed three typos

---

_posts/2021-01-04-dynamic-test-oracles-for-rho-problems.html

Haskell => Hedgehog

---

_posts/2018-12-03-set-is-not-a-functor.html

Hi again, I'm still plowing though your excellent Functional Series and thought of some Resolutions to the broken functor Laws of HashSet. 
I think the Difference between weak Equality and strong Identity ist important here.

Possible Restoration of Functor Law for HashSets

---

_posts/2011-05-24-DesignSmellTemporalCoupling.html

Added comment.
First time commenting so apologies if the formatting is incorrect!

Comment on 'Design Smell: Temporal Coupling' 

---

_posts/2021-06-14-new-book-code-that-fits-in-your-head.html

A new comment about when the book would be generally available in Europe.

Comment: book availability in europe

---

_posts/2015-01-15-10-tips-for-better-pull-requests.html

A comment / question on the "10 Tips for Better Pull Requests" article.

Comment on "10 Tips for Better Pull Requests"

---

_posts/2017-11-13-endomorphism-monoid.html

Hi Mark,
A brief comment to your post about endomorphisms and monoids from 2017. Hoping you're up for a reply.

Add comment to endomorphism monoid post

---

_posts/2022-01-17-enumerate-wordle-combinations-with-an-applicative-functor.html

It's not "better", but here's a similar approach in Python

Add comment with similar approach in Python

---

_posts/2013-06-24-a-heuristic-for-formatting-code-according-to-the-aaa-pattern.html

I don't find a proper way to format my snippet. How do you proceed?
Is there a way to embed a gist?

Local function to enforce balance

---

_posts/2017-10-30-tuple-monoids.html

2017-10-30-tuple-monoids fix typos

---

_posts/2014-08-11-cqs-versus-server-generated-ids.html

Hello! Wonderful book, wonderful blog. Hoping to get your opinion on some thoughts I had about CQS and DDD as I read through the API chapter in _Code That Fits in Your Head_.
Appreciate all that you do to help inexperienced developers like myself learn and grow into professionals.

Ask question regarding DDD, CQS, and if Commands can return informational data

---

_posts/2015-05-07-functional-design-is-intrinsically-testable.html

Deeper explanation of random testing with constrained static types.
The code blocks are a bit awkward. I can find a way to colorize them and eliminate extra spacing if you'd like.

Explain background of spec-like testing

---

_posts/2022-05-23-waiting-to-never-happen.html

Comment added to 'Waiting to never happen' post

Comment added to 'Waiting to never happen' post

---

assets/themes/css/style.css
assets/themes/ploeh/css/style.css

Fix #605
Ran this locally, everything looks good :) the permalink now "appears" when the user hovers over the corresponding header.

Permalink hover

---

_posts/2022-07-25-an-applicative-reservation-validation-example-in-c.html

I wasn't sure how to generate a comment ID, so you'll have to update that for me.

Add comment to blog post of 2022-07-25

---

_posts/2022-08-22-can-types-replace-validation.html

I hope I got the code formatting right

Add a comment to "Can types replace validation"

---

_posts/2022-09-19-when-to-refactor.html

I read in an article one time:
> Every time you see something that could be improved, why not improve it?

Fix typo in calendar

---

_posts/2022-10-24-encapsulation-in-functional-programming.html

This PR fixes the sample code colors (red was accidental) in the comment added with PR #849.

Fix colors in example code (from #849)

---

_posts/2023-01-02-adding-nuget-packages-when-offline.html

That is how it's also written in the docs, as it seems: https://learn.microsoft.com/en-us/windows/win32/shell/csidl

Change appdata to AppData

---

_posts/2023-02-06-contravariant-functors-as-invariant-functors.html

Typo exammple -> example

---

_posts/2023-02-13-epistemology-of-interaction-testing.html

* sorry for the bother, but I'm trying to keep this more consistent across my online presence

Changing the spelling of the last name: Rogovtsev -> Rogovtcev

---

_posts/2023-04-03-an-abstract-example-of-refactoring-from-interaction-based-to-property-based-testing.html

Sorry the code needs some style

CsCheck comment code style

---

_posts/2023-04-03-an-abstract-example-of-refactoring-from-interaction-based-to-property-based-testing.html

CsCheck comment fix whitespace

---

_posts/2023-06-12-collatz-sequences-by-function-composition.html

Also removed an extra space in a predicate passed to TakeWhile in the main article.

Add comment about conditions needed to test a recursive step

---

_posts/2023-07-17-works-on-most-machines.html

added a comment for works-on-most-machines post

---

_posts/2023-09-18-do-orms-reduce-the-need-for-mapping.html

qfilip comment

---

_posts/2023-09-18-do-orms-reduce-the-need-for-mapping.html

Additional thoughts, after some experimentation

yet another comment

---

_posts/2023-10-02-dependency-whac-a-mole.html

Adding some reflections on the post.

Add comment to 2023-10-02-dependency-whac-a-mole.html

---

_posts/2023-09-18-do-orms-reduce-the-need-for-mapping.html

I'm hoping these PRs aren't taking too much of your time :)

replying to opcoder

---

_posts/2023-09-18-do-orms-reduce-the-need-for-mapping.html

Just my cents about this issue.

Add comment on Do ORMs reduce the need for mapping?

---

_posts/2018-04-23-null-object-as-identity.html

Leave comment on the post 2018-04-23-null-object-as-identity

comment on 2018-04-23-null-object-as-identity

---

_posts/2023-10-09-whats-a-sandwich.html

requesting mayonnaise for the sandwich

---

_posts/2023-12-25-serializing-restaurant-tables-in-c.html

Added a comment discussing the utility of `System.Text.Json`.

Add thoughts on 2023-12-25-serializing-restaurant-tables-in-c.html

---

_posts/2010-02-03-ServiceLocatorisanAnti-Pattern.html
_posts/2023-08-14-replacing-mock-and-stub-with-a-fake.html

Hi Mark,
I previously posted my question regarding Fakes and test exceptions in X on Twitter. As you suggested, I've now created a pull request on the blog, albeit with a slight delay. I hope this aligns with the correct structure you were expecting. Additionally, I've included more details regarding the question.
Please inform me if further changes or additional details are required.
Thanks,
Amir

Add a comment for the replacing-mock-and-stub-with-a-fake article

---

_posts/2024-06-03-youll-regret-using-natural-keys.html

Adding my thoughts on having two id keys in tables

Two keys are good

---

_posts/2024-06-03-youll-regret-using-natural-keys.html

Bare URLs on the web are a pain for UX. Just fixing that.

Fix URLs in comment

---

_posts/2024-06-12-simpler-encapsulation-with-immutability.html

Added comment to 2024-06-12-simpler-encapsulation-with-immutability.

Add comment on post dated 2024-06-12

---

_posts/2024-06-12-simpler-encapsulation-with-immutability.html

Add comment on 2024-06-12-simpler-encapsulation-with-immutability

Add reader comment

---

_posts/2024-06-17-a-failed-attempt-at-priority-collection-with-inheritance.html

Perhaps stupid to try the same approach you took but I had to see it through
Comment on failure.

Comment to "A failed attempt at priority collection with inheritance"

---

_posts/2024-06-03-youll-regret-using-natural-keys.html

Hi,
I thought I may add one of my experiences here. While a join table might not be the focus of the post, you never know when a join table might start to become more relevant.

Add comment for natural keys

---

_posts/2024-07-01-an-immutable-priority-collection.html

Just a quick comment saying I liked this article, and mentioning the generic `with` projection.

Add comment to 2024-07-01-an-immutable-priority-collection.html

---

_posts/2024-08-12-using-only-a-domain-model-to-persist-restaurant-table-configurations.html

Add a comment with question to article published 2024-08-12

Add article commit

---

_posts/2024-10-03-das-verflixte-hunde-spiel.html

I can't say that this is the most convenient way to write comments, but it definitely has its advantages. It also made me learn about the VSCode [Remote repositories extension](https://marketplace.visualstudio.com/items?itemName=GitHub.remotehub&WT.mc_id=devcloud-18509-cxa), so I wouldn't have to clone your repo just to write a comment.

Comment on Das verflixte Hunde-Spiel

---

_posts/2025-04-01-ports-and-fat-adapters.html

Not sure if I need to come up with new ids(as long as they're unique for that post). If so, let me know and I'll fix it.

Commenting on 2025-04-01-ports-and-fat-adapters.html
