_posts/2015-01-19-from-primitive-obsession-to-domain-modelling.html

Although UserName is stated to be case-insensitive, does this necessarily mean that one must pass all uppercase to the constructor? That doesn't seem right.

Question: instantiating UserName with lowercase

---

_posts/2015-04-13-less-is-more-language-features.html

I know const isnt water tight but idiomatic C++ does use const to 'guarantee no changes'

Fixed Typos

---

_includes/themes/ploeh/atom.xml
_includes/themes/ploeh/rss.xml

As discussed on twitter and mentioned via my [blog](http://taeguk.co.uk/blog/dealing-with-newsblur-and-large-feeds/), NewsBlur has problems with large RSS / Atom feeds. Jekyll supports limiting the number of posts in the feed. I've picked 10 as an arbitrary number.

Limiting Atom and RSS feeds to 10 posts

---

_posts/2015-09-18-temporary-field-code-smell.html

Hi Mark!
I spotted a small typo in your latest blog post and here's the fix.
Thanks for the post! The Estimator is indeed a good example.

fixed typo

---

_posts/2015-09-21-public-types-hidden-in-plain-sight.html

This looks like a typo, assume it should be 618 both places instead of 681 on the restore.

Typo: Pragma disable/restore mismatch

---

_posts/2014-05-15-service-locator-violates-solid.html

I added another comment explaining why clients should be aware when they target an O-O or Metaprogramming API.

added another comment to "Service Locator violates SOLID"

---

_posts/2013-05-01-rest-lesson-learned-avoid-hackable-urls.html

I argue that hackable URLs should not be avoided at any cost, especially not if the workaround makes the API more complex.

Comment on using POST to avoid hackability

---

_posts/2016-09-26-decoupling-decisions-from-effects.html

so that the `Result` module compiles.
Hopefully, this makes it easier for readers to just copy and paste, and compile the source code using their favorite code editor or IDE.

Added Result union type,

---

_posts/2017-08-28-the-builder-functor.html

"A functor is a simple, but widely applicably abstraction." should be "A functor is a simple, but widely applicable abstraction."

typo "applicably" should be "applicable"

---

_posts/2017-11-13-endomorphism-monoid.html

I puzzled for a while over the original sentence, "Methods that return the same type of value as their input form monoids" because my initial interpretation was that you were considering methods with two arguments and that those would constitute the monoid's binary operator. Since monoids require two things - a set and a binary operation over that set - and the sentence in question talks about two things - values of a particular type, and methods that operate on them - that seemed like the natural way to interpret the sentence.
However, obviously not all such (methods + value sets) form monoids. So I eventually guessed that what you actually meant is that the methods are the monoid's set, and that you've left it as an exercise for the reader to work out what operator(s) you had in mind. …

Add missing binary operation from example monoid

---

_posts/2018-07-02-terse-operators-make-business-code-more-readable.html

At *"Second, there seems [?] some calculations"* it looks like something is missing.
---
Great article, by the way. Looking at this:
```haskell
tryAccept :: Int -> Reservation -> MaybeT ReservationsProgram Int
```
I wonder why the full source code isn't somewhere online (GitHub, GitHub Gist). Or it already is? Myself, but perhaps also others, could have a look at the whole source code.

Add missing word

---

_posts/2018-09-17-typing-is-not-a-programming-bottleneck.html

<div class="comment" id="">
<div class="comment-author"><a href="https://davideguida.com">Davide Guida</a></div>
<div class="comment-content">
Lines of code have nothing to do with productivity. As professionals I think we all know this. <br />
Moreover, in many cases, too much verbosity might only lead to more defects (unless you're a strong advocate of TDD et similia)<br />
That said, one thing that I really liked about your article is the version of the Builder pattern you've implemented in the Reservation class. 
I love immutability in my classes and I often use the Builder pattern implemented as a inner class, just to be able to access the private cTor (got an example on my blog BTW). <br/>
One thing that I don't like with your approach is that in case you have a big parameter list …

added my comment

---

_posts/2016-02-10-types--properties--software.html

Removed two (spliced) commas and changed "is" to "are" to have the verb match the multiplicity of the subject.

improved grammar

---

_posts/2020-02-03-non-exceptional-averages.html

Thanks for fixing my 12-hour for 24-hour typo.  Here is my attempt to remove the extra indentation in my comment.  If you want, feel free to make additional modifications if I still didn't get the formatting to look good.

fix formatting of comment about overflow

---

_posts/2018-03-26-the-maybe-functor.html

> I think it's interesting to note that since C# 8.0 we don't require an extra generic type like `Maybe<T>` anymore in order to implement the maybe functor. Because C# 8.0 added nullable reference types, everything can be nullable now. By adding the right extension methods we can make `T?` a maybe functor and use its beautifully succinct syntax.
>
> Due to the C#'s awkward dichotomy between value and reference types this involves some busy work, so I created a [small nuget package](https://github.com/bert2/Nullable.Extensions) for interested parties.

add comment to "The Maybe functor" post

---

_posts/2020-07-06-referential-transparency-of-io.html

> You can get around the issue using the language's wildcard pattern. This tells the compiler that you're actively ignoring the result of the action.
You made a standard variable declaration and I believe you meant to use a [stand-alone discard] rather than a wildcard pattern? Like below?
[stand-alone discard]: https://docs.microsoft.com/en-us/dotnet/csharp/discards#a-standalone-discard
```c#
public static string Greet(DateTime now, string name)
{
_ = Console.WriteLine("Side effect!");
var greeting = "Hello";
if (IsMorning(now))
greeting = "Good morning";
if (IsAfternoon(now))
greeting = "Good afternoon";
if (IsEvening(now))
greeting = "Good evening";
if (string.IsNullOrWhiteSpace(name))
return $"{greeting}.";
return $"{greeting}, {name.Trim()}.";
}
```

Referential transparency of IO: You mean discard?

---

_posts/2016-04-11-async-as-surrogate-io.html

Instead of replacing "were" with "was", another fix is to replace "communication" with "communications".

fixed typo by replacing "were" with "was"

---

_posts/2013-05-01-rest-lesson-learned-avoid-hackable-urls.html

This PR replaces one occurrence of "order" with "orders".  I think "orders" was intended, but maybe I misunderstood something.

Fix typo order to orders

---

_posts/2017-10-06-monoids.html

This PR contains a small change, aimed to provide a slightly more precise definition of a monoid.
In the beginning of your post series you mention that 
> a monoid is a combination of a data type (or set) and an operation.
From there on, though, it seems that you conflate the two components and you only refer to monoids other algebraic structures just as "operations":
> A monoid (not to be confused with a monad) is a binary operation
> Semigroups form a superset of monoids. They are associative binary operations.
That's not quite right. Semigroups are not functions, and they are possibly better described as "algebraic structures consisting of a set together with an associative binary operation".
I think in the narrative this could be a convenient simplification, especially since in FP we …

Specified that a monoid is a set + an operation

---

_posts/2017-01-27-dependency-injection-is-passing-an-argument.html

Adds a comment on `dependency-injection-is-passing-an-argument` in regards to using the `[FromServices]` attribute for injecting dependencies in controllers as method arguments.

Comment about using the new [FromServices] for DI

---

_posts/2020-07-27-task-asynchronous-programming-as-an-io-surrogate.html

Hi, your IO<T> C# Class was very instructive. 
I tried to close the gap you mentioned of Tasks already running and performing side-effects even when their result is ignored 
and found a working SelectMany Implementation that evaluates the Task lazily and only once. 
The idea is to consistently return Tasks that are NOT started and leave it to the Boundary Code to call await and thus trigger all Side Effects. 
I think it would be worth adopting such a practice, at least personally. What do you think?

Using new Task<T>s that are not started to enforce Method purity

---

_posts/2017-01-27-from-dependency-injection-to-dependency-rejection.html
_posts/2017-02-02-dependency-rejection.html
_posts/2017-07-10-pure-interactions.html
_posts/2017-07-11-hello-pure-command-line-interaction.html
_posts/2019-08-26-functional-file-system.html
_posts/2019-09-09-picture-archivist-in-haskell.html
_posts/2019-09-16-picture-archivist-in-f.html
_posts/2019-12-02-refactoring-registration-flow-to-functional-architecture.html

Resolves #716
This PR adds forward links to the [impureium sandwich article](https://blog.ploeh.dk/2020/03/02/impureim-sandwich/) (i.e. links to that article from articles written before it).  I searched for `sandwich` and added the link at most once per article at the first "available" occurrence (i.e. not in the description or text that already contained a link).
Here are all the articles that include the world `sandwich` but I did not add a link...and the reason why.
1. [`2017-08-07-f-free-monad-recipe.html`](https://blog.ploeh.dk/2017/08/07/f-free-monad-recipe/) (2 hits): Both already link to [`2017/07/10/pure-interactions`](https://blog.ploeh.dk/2017/07/10/pure-interactions/)
2. [`2018-11-19-functional-architecture-a-definition.html` …

added forward links to impureium sandwich article

---

_posts/2009-01-28-Zero-FrictionTDD.html

Microsoft must have moved domains from blogs.msdn.com to docs.microsoft.com. The link structure also changed and specific post links didn't forward correctly.

Fix broken links pointing to MSDN blog

---

_posts/2022-01-17-enumerate-wordle-combinations-with-an-applicative-functor.html

@ploeh thanks for suggesting that I use my GitHub profile as the comment author link. That didn't occur to me.

Add personal URL to existing comment

---

_posts/2017-10-16-money-monoid.html

Wasn't sure whether to use `&gt;` or raw `>` 🤷

2017-10-16-money-monoid comment

---

_posts/2022-02-28-can-one-flatten-a-statically-typed-list.html

Is there a way to generate or preview these comments? I tried following examples, but I have no idea if this is right

Add comment on flattening statically typed lists

---

_posts/2022-05-09-an-either-monad.html

It seems like variable `foo` in AssociativityLaw function remained unused

Typo in 2022-05-09-an-either-monad

---

_posts/2017-10-16-money-monoid.html

Semigroup as a superclass of Monoid
---
Full example, as a sanity check, not included in the comment:
```hs
-- *** Money monoid
-- https://blog.ploeh.dk/2017/10/16/money-monoid/
{-# LANGUAGE CPP #-}
import           Data.Map.Strict (Map, (!))
import qualified Data.Map.Strict as Map
import           Data.Semigroup (stimesMonoid)
#if !MIN_VERSION_base(4,11,0)
import qualified Data.Semigroup as Semigroup
#endif
instance Monoid Expression where
#if !MIN_VERSION_base(4,11,0)
mappend =
(Semigroup.<>)
#endif
mempty =
MoneyIdentity
instance Semigroup Expression where
MoneyIdentity <> y =
y
x <> MoneyIdentity =
x
x <> y =
Sum x y
data Expression =
Money {
amount :: Int
, currency :: String
}
| Sum {
augend :: Expression
, addend :: Expression
}
| MoneyIdentity
reduce :: Ord a => Map (String, a) …
```

Update Haskell part of Money Monoid

---

_posts/2022-10-24-encapsulation-in-functional-programming.html

This PR adds the following comment to [Encapsulation in Functional Programming](https://blog.ploeh.dk/2022/10/24/encapsulation-in-functional-programming/):
> I wonder what's the goal of illustrating OOP-ish examples exclusively in C# and FP-ish ones in F# when you could stick to just one language for the reader. It might not always be as effective depending on the topic, but for encapsulation and the examples shown in this article, a C# version would read just as effective as an F# one. I mean when you get round to making your points in the **Immutable Table** section of your article, you could demonstrate the ideas with a C# version that's nearly identical to and reads as succinct as the F# version:
>
> ```c#
> #nullable enable
>
> readonly record struct Reservation(int Quantity);
> …
```

Encapsulation: comment about demonstrating whole idea in one language

---

_posts/2022-10-24-encapsulation-in-functional-programming.html

This PR adds a comment to https://blog.ploeh.dk/2022/10/24/encapsulation-in-functional-programming/ about encapsulating the subtypes to `Table` as outlined in [atifaziz' comment.](https://github.com/ploeh/ploeh.github.com/pull/849#issue-1425907896)
I apologize for the messy code; I couldn't get Jekyll to build the page with proper syntax highlighting or formatting. I'll make changes if necessary.

Encapsulation: comment about encapsulating `Table` subtypes

---

_posts/2022-12-12-when-do-tests-fail.html

Added "when" to line 85, and added "a" to line 169.

Fix two typos in "When do tests fail?"

---

_includes/themes/ploeh/default.html

Pages already have the twitter specific tags that enhance the way the link preview is rendered if a link is posted there, but they are not supported by all platforms. This adds the corresponding open graph tags that serve the same function on other sites (including Mastodon which is where I noticed this discrepancy)

Add open graph meta tags

---

_posts/2023-12-04-serialization-with-and-without-reflection.html

Haskell has reflection through [Typeable](https://hackage.haskell.org/package/base-4.19.0.0/docs/Data-Typeable.html#t:Typeable), however it's not widely use.
I tend to use it at the boundaries of my Domain, when I have runtime types uncertainty.
I agree that they are not used for serialization (as far as I know), and that the RTS does not have enough knowledge on the types it deals with (and we cannot access to what it knows).

Precise:  Serialization w/ & without Reflection
